#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""batin.py: Bug hunting on the Ethereum blockchain
   http://www.github.com/b-mueller/mythril
   """
from sys import exit
import batin.interfaces.cli
import time

if __name__ == "__main__":
    batin.interfaces.cli.main()
    exit()





